import { sql } from "drizzle-orm";
import { jsonb, pgTable, text, timestamp, unique, uuid } from "drizzle-orm/pg-core";
import { tenants } from "./tenants";
import type { MemberId, TenantId } from "@/lib/ids";

// R.8 — absence_alerts. Drizzle mirror of
// db/migrations/20260913000300_absence_alerts.sql. Alerts are
// generated by the daily job and read-only to users; the unique key is
// the dedupe contract (one alert per member/batch/kind/week).
export const absenceAlerts = pgTable(
  "absence_alerts",
  {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    tenantId: uuid("tenant_id")
      .notNull()
      .references(() => tenants.id, { onDelete: "cascade" })
      .$type<TenantId>(),
    memberId: uuid("member_id").notNull().$type<MemberId>(),
    batchId: uuid("batch_id").notNull(),
    alertKind: text("alert_kind").notNull(),
    calendarWeek: text("calendar_week").notNull(),
    detail: jsonb("detail").$type<Record<string, unknown>>(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    unique("absence_alerts_dedupe_key").on(
      t.tenantId,
      t.memberId,
      t.batchId,
      t.alertKind,
      t.calendarWeek,
    ),
  ],
);

export type AbsenceAlert = typeof absenceAlerts.$inferSelect;
export type AbsenceAlertKind = "consecutive_absences" | "low_monthly_attendance";
